# Generated by Django 5.0.7 on 2024-08-17 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_contact_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='civility',
            field=models.CharField(default=False, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contact',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='contacts/%Y/%m/%d/'),
        ),
    ]
